nome=input('Qual seu nome?')
print('Olá',nome+'! Prazer em te conhecer!')
dia=input('Qual o dia de seu nascimento?')
mês=input('Qual o mês de seu nascimneto?')
ano=input('Qual o ano de seu nascimneto?')
print('Você nasceu no dia',dia,'de',mês,'de',ano+'!')
n1=input('Diga o primeiro número:')
n2=input('Diga o segundo número:')
soma=int(n1)+int(n2)
print('A soma desses 2 números é:',soma)
